### PR TITLE
Update lambdas/build-stac Dockerfile

### PR DESCRIPTION
**Pull request by emileten**
Specify the platform to avoid Apple chip issues when doing local development.

### CODE REVIEW

**Comment by emileten** [comment]
@jjfrench I encountered the same bug as you did here : https://github.com/NASA-IMPACT/active-maap-sprint/issues/443#issuecomment-1443821296.

I think this shouldn't create problems in the deployments ? I am not entirely sure

**Comment by jjfrench** [comment]
> @jjfrench I encountered the same bug as you did here : [NASA-IMPACT/active-maap-sprint#443 (comment)](https://github.com/NASA-IMPACT/active-maap-sprint/issues/443#issuecomment-1443821296).
> 
> I think this shouldn't create problems in the deployments ? I am not entirely sure

@emileten Did you hit it for multiple lambdas or just the one? I think there were two rasterio requirements in files. I added it to every dockerfile in the end due to some of the error messages I was seeing after deployment

**Comment by emileten** [comment]
@jjfrench I encountered it in that lambda only. Didn't run all of the lambdas today though.

**Comment by jjfrench** [comment]
Might be worth adding it to all or finding a way to enforce it across all lambda builds

**Review by jjfrench — APPROVED** [review]

**Comment by emileten** [comment]
We _might_ be able to use the `platform` parameter of https://docs.aws.amazon.com/cdk/api/v1/python/aws_cdk.aws_lambda/Code.html#aws_cdk.aws_lambda.Code.from_asset_image

**Comment by emileten** [comment]
> finding a way to enforce it across all lambda builds

When I changed a couple but not all the lambda's dockerfiles to have this platform parameter value specified, I indeed encoutered errors.

Closing this as it's not creating headaches in our everyday usage of this repo, and don't have the time to figure this out now, but we might need to keep a note somewhere.

**Pull request closed without merging**
